const {downloadFiles} = require('@ekx/cli-utils');

async function run() {
    await downloadFiles({
        srcBaseUrl: "https://github.com/wolfpld/tracy/raw/master",
        destPath: "src",
        fileList: [
            "Tracy.hpp",
            "TracyClient.cpp",
            "common/tracy_lz4.cpp",
            "common/tracy_lz4.hpp",
            "common/tracy_lz4hc.cpp",
            "common/tracy_lz4hc.hpp",
            "common/TracyAlign.hpp",
            "common/TracyAlloc.hpp",
            "common/TracyApi.h",
            "common/TracyColor.hpp",
            "common/TracyForceInline.hpp",
            "common/TracyMutex.hpp",
            "common/TracyProtocol.hpp",
            "common/TracyQueue.hpp",
            "common/TracySocket.cpp",
            "common/TracySocket.hpp",
            "common/TracySystem.cpp",
            "common/TracySystem.hpp",
            "common/TracyYield.hpp",
            "common/TracyYield.cpp",
            "common/TracyStackFrames.hpp",
            "common/TracyStackFrames.cpp",
            "client/TracyAlloc.cpp",
            "client/TracyLock.hpp",
            "client/TracyProfiler.hpp",
            "client/TracyScoped.hpp",
            "client/tracy_rpmalloc.hpp",
            "client/tracy_concurrentqueue.h",
            "client/TracyCallstack.hpp",
            "client/TracySysTime.hpp",
            "client/TracyFastVector.hpp",
            "client/TracyCallstack.h",
            "client/TracyProfiler.cpp",
            "client/TracyCallstack.cpp",
            "client/TracySysTime.cpp",
            "client/TracySysTrace.cpp",
            "client/TracySysTracePayload.hpp",
            "client/TracyDebug.hpp",
            "client/tracy_rpmalloc.cpp",
            "client/TracyDxt1.cpp",
            "client/TracyDxt1.hpp",
            "client/TracyThread.hpp",
            "client/TracyArmCpuTable.hpp",
            "client/TracySysTrace.hpp",
            "client/TracyRingBuffer.hpp",
            "TracyC.h",
            "libbacktrace/backtrace.hpp",
            "libbacktrace/alloc.cpp",
            "libbacktrace/dwarf.cpp",
            "libbacktrace/fileline.cpp",
            "libbacktrace/mmapio.cpp",
            "libbacktrace/posix.cpp",
            "libbacktrace/sort.cpp",
            "libbacktrace/state.cpp",
            "libbacktrace/macho.cpp",
            "libbacktrace/config.h",
            "libbacktrace/internal.hpp",
            "libbacktrace/filenames.hpp",
            "libbacktrace/elf.cpp"
        ]
    });
}

run().catch(() => process.exit(1));